spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/makerspace
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    properites:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    root: info
    org.hibernate.sql: debug